### ISSUE TITLE
Typo in https://bomb.codes/bombs Images bytes calculation

### ISSUE THREAD

**Issue by nigeltao** [bones-codes/bombs#2]
Quoting https://bomb.codes/bombs and its "Images" section:

> a 50Kx50K pixel, 8-bit (RGB) image will require about 2.5GB (50,000 x 50,000 x 1 byte = 250,000,000 bytes).

The 2.5GB number is right, but the final number is missing a zero (and therefore another comma).

**Comment by bones-codes** [comment]
Thanks!

**Comment by bones-codes** [comment]
Excellent catch – updated! Thanks!
